suffix_main: my_suffix.o suffix_main.o
	gcc -ansi -Wall -pedantic suffix_main.c -o suffix_main
my_suffix.o: my_suffix.c
	gcc -c -ansi -Wall -pedantic my_suffix.c -o my_suffix.o
suffix_main.o: suffix_main.c
	gcc -c -ansi -Wall -pedantic suffix_main.c -o suffix_main.o
